const userData = {
  userId: 1,
  name: "Niraj Mahajan",
  email: "niraj@example.com",
  phone: "00000 0000",
  profileImage: "",
  dateOfBirth: "2000-01-01",
  gender: "Male",
  joinedDate: "2023-08-21",
  wishlist: [
    {
      productId: 101,
      productName: "Dell XPS 15",
      company: "Dell",
      price: 150000,
      productImage: "https://via.placeholder.com/150",
      productDescription: "Dell high performance laptop",
    },
    {
      productId: 102,
      productName: "Dell Alienware M15 R6",
      company: "Dell",
      price: 175000,
      productImage: "https://via.placeholder.com/150",
      productDescription: "High-end gaming laptop",
    },
    {
      productId: 103,
      productName: "MacBook Air M3",
      company: "Apple",
      price: 125000,
      productImage: "https://via.placeholder.com/150",
      productDescription: "Latest Apple silicon-powered MacBook Air",
    },
    {
      productId: 104,
      productName: "MacBook Pro M2",
      company: "Apple",
      price: 200000,
      productImage: "https://via.placeholder.com/150",
      productDescription: "Powerful MacBook Pro for professionals",
    },
    {
      productId: 105,
      productName: "HP Spectre x360",
      company: "HP",
      price: 130000,
      productImage: "https://via.placeholder.com/150",
      productDescription: "Convertible HP laptop",
    },
    {
      productId: 106,
      productName: "Lenovo Legion 5",
      company: "Lenovo",
      price: 140000,
      productImage: "https://via.placeholder.com/150",
      productDescription: "Gaming laptop from Lenovo",
    },
    {
      productId: 107,
      productName: "Asus ROG Strix",
      company: "Asus",
      price: 160000,
      productImage: "https://via.placeholder.com/150",
      productDescription: "Asus gaming beast",
    },
  ],
  orders: [
    { orderId: "ORD12345", orderDate: "2025-09-01", status: "Delivered", totalAmount: 115000 },
    { orderId: "ORD12346", orderDate: "2025-09-10", status: "Shipped", totalAmount: 55000 },
  ],
  settings: { language: "English", currency: "INR", darkMode: false },
};

export default userData;
